-- =============================================================================
-- VereHire AI — New Database Schema (Spring Boot Managed)
-- =============================================================================
-- Run this script in your Supabase SQL Editor ONCE before starting Spring Boot.
--
-- What this script does:
--   1. Drops old Supabase-auth-dependent objects safely
--   2. Creates a 'users' table (Spring Boot owns authentication)
--   3. Creates 'jobs' table with status column and reference to public.users
--   4. Creates 'candidates' table
--   5. Disables RLS (Spring Boot enforces user data isolation in application layer)
-- =============================================================================

-- =============================================================================
-- STEP 1: Safe Cleanup of old objects
-- =============================================================================

-- Drop RLS policies safely inside a DO block so it never fails if tables don't exist
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'jobs') THEN
        DROP POLICY IF EXISTS "Users can view their own jobs" ON public.jobs;
        DROP POLICY IF EXISTS "Users can insert their own jobs" ON public.jobs;
        DROP POLICY IF EXISTS "Users can update their own jobs" ON public.jobs;
        DROP POLICY IF EXISTS "Users can delete their own jobs" ON public.jobs;
        DROP TRIGGER IF EXISTS update_jobs_updated_at ON public.jobs;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'candidates') THEN
        DROP POLICY IF EXISTS "Users can view candidates from their jobs" ON public.candidates;
        DROP POLICY IF EXISTS "Users can insert candidates to their jobs" ON public.candidates;
        DROP POLICY IF EXISTS "Users can update candidates in their jobs" ON public.candidates;
        DROP POLICY IF EXISTS "Users can delete candidates from their jobs" ON public.candidates;
    END IF;
END $$;

-- Drop functions
DROP FUNCTION IF EXISTS get_job_with_stats(TEXT) CASCADE;
DROP FUNCTION IF EXISTS delete_expired_jobs() CASCADE;
DROP FUNCTION IF EXISTS update_updated_at_column() CASCADE;

-- Drop old tables in dependency order
DROP TABLE IF EXISTS public.candidates CASCADE;
DROP TABLE IF EXISTS public.jobs CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

-- =============================================================================
-- STEP 2: Create users table (Spring Boot owns authentication)
-- =============================================================================

CREATE TABLE public.users (
    id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    email         TEXT         NOT NULL UNIQUE,
    password_hash TEXT         NOT NULL,    -- BCrypt hash, managed by Spring Boot
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_users_email ON public.users(email);

COMMENT ON TABLE public.users IS 'Recruiter accounts. Managed entirely by Spring Boot (BCrypt + JWT).';

-- =============================================================================
-- STEP 3: Create jobs table
-- =============================================================================

CREATE TABLE public.jobs (
    id                UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    job_id            TEXT         NOT NULL UNIQUE,     -- 8-char hex ID, generated by Spring Boot
    user_id           UUID         NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    job_description   TEXT         NOT NULL DEFAULT '',
    status            TEXT         NOT NULL DEFAULT 'PROCESSING'
                                   CHECK (status IN ('PROCESSING', 'COMPLETED', 'FAILED')),
    error_message     TEXT,                             -- Populated when status = FAILED
    total_candidates  INTEGER,                          -- Populated when status = COMPLETED
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_jobs_user_id ON public.jobs(user_id);
CREATE INDEX idx_jobs_job_id  ON public.jobs(job_id);
CREATE INDEX idx_jobs_status  ON public.jobs(user_id, status);

COMMENT ON TABLE public.jobs IS 'Ranking jobs submitted by recruiters.';

-- Auto-update updated_at timestamp trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_jobs_updated_at
    BEFORE UPDATE ON public.jobs
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- =============================================================================
-- STEP 4: Create candidates table
-- =============================================================================

CREATE TABLE public.candidates (
    id                UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    job_id            TEXT         NOT NULL,            -- References jobs.job_id
    candidate_id      TEXT         NOT NULL,            -- Candidate ID from uploaded CSV
    name              TEXT         NOT NULL DEFAULT '',
    email             TEXT         NOT NULL DEFAULT '',
    role              TEXT         NOT NULL DEFAULT '',
    rank              INTEGER      NOT NULL DEFAULT 1,
    percentile        INTEGER      NOT NULL DEFAULT 0,
    pr_score          INTEGER      NOT NULL DEFAULT 0,
    github_score      INTEGER      NOT NULL DEFAULT 0,
    dsa_score         INTEGER      NOT NULL DEFAULT 0,
    verdict           TEXT         NOT NULL DEFAULT 'REJECT'
                                   CHECK (verdict IN ('HIRE', 'REVIEW', 'REJECT')),

    -- Rich JSONB fields stored as JSON
    skills            JSONB        NOT NULL DEFAULT '[]'::jsonb,
    github_evidence   JSONB        NOT NULL DEFAULT '{}'::jsonb,
    leetcode          JSONB        NOT NULL DEFAULT '{}'::jsonb,
    codeforces        JSONB,                            -- Optional: null if candidate has no CF profile
    timeline          JSONB        NOT NULL DEFAULT '[]'::jsonb,
    risk_flags        JSONB        NOT NULL DEFAULT '[]'::jsonb,

    summary           TEXT         NOT NULL DEFAULT '',
    layer1_score      DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    layer2_score      DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    layer3_confidence DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT candidates_job_candidate_unique UNIQUE (job_id, candidate_id)
);

CREATE INDEX idx_candidates_job_id   ON public.candidates(job_id);
CREATE INDEX idx_candidates_rank     ON public.candidates(job_id, rank);
CREATE INDEX idx_candidates_verdict  ON public.candidates(job_id, verdict);
CREATE INDEX idx_candidates_pr_score ON public.candidates(job_id, pr_score);

-- =============================================================================
-- STEP 5: Explicitly disable RLS
-- =============================================================================
-- Spring Boot is the single owner of the database.
-- Application layer enforces: WHERE user_id = :authenticated_user_id.

ALTER TABLE public.users      DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.jobs       DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.candidates DISABLE ROW LEVEL SECURITY;

-- Grant permissions to public/anon/authenticated roles
GRANT ALL ON TABLE public.users      TO anon, authenticated, service_role, postgres;
GRANT ALL ON TABLE public.jobs       TO anon, authenticated, service_role, postgres;
GRANT ALL ON TABLE public.candidates TO anon, authenticated, service_role, postgres;

-- =============================================================================
-- STEP 6: Create user_settings table for BYOK
-- =============================================================================
CREATE TABLE public.user_settings (
    id                     UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                UUID         NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
    github_token_encrypted TEXT,
    ai_provider            TEXT         NOT NULL DEFAULT 'groq'
                                        CHECK (ai_provider IN ('groq', 'ollama')),
    groq_api_key_encrypted TEXT,
    ollama_base_url        TEXT,
    created_at             TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at             TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TRIGGER update_user_settings_updated_at
    BEFORE UPDATE ON public.user_settings
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE public.user_settings DISABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE public.user_settings TO anon, authenticated, service_role, postgres;
